title: Shen's tech blog
author: Shen Tian
email: biozinc@gmail.com
description: >
  Tinkerer, Capetownian, Runner, Burner
baseurl: ""
url: "https://shentian.me"
google_analytics: G-PPC6306M88

github_username: shen-tian
linkedin_username: shentian
instagram_username: shen.tian

markdown: kramdown
kramdown:
  input: GFM
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
exclude:
  - Gemfile
  - Gemfile.lock
  - CLAUDE.md

picture:
  source: "assets/images"
  output: "generated"
